FROM python:3.9-slim-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements-old.txt .
RUN pip install -r requirements-old.txt

# Run the application:
COPY main.py .
COPY app.py .

CMD ["python", "main.py"] & ["streamlit", "run", "app.py"]